tesseract:
  executable_path: null  # e.g. "C:/Program Files/Tesseract-OCR/tesseract.exe" on Windows

doctr:
  detector_model: "db_resnet50"

paths:
  lexicon_file: null
  debug_dir: "debug"

preprocess:
  target_height: 1600
  target_width: 1200
  adaptive_threshold_block_size: 31
  adaptive_threshold_C: 10

debug:
  enabled_default: false
